update crowdin.yml, CHANGELOG.md, ro.json and it.json files
vtex/address-form pull request #302
Opened 2020-11-16 13:09 UTC by camilavcoutinho

#### What is the purpose of this pull request?

update RO and IT translations

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2020-12-08 19:44 UTC, alvim approved these changes

2020-12-08 19:47 UTC, paul0vinicius submitted a review, later dismissed
LGTM ✨

2020-12-08 20:23 UTC, dvm1984 requested changes
de onde surgiram essas mudancas para romeno> Estao erradas

2020-12-08 22:59 UTC, dvm1984 submitted a review, later dismissed

2020-12-16 18:03 UTC, dvm1984 approved these changes

2020-12-16 18:38 UTC, wdsrocha commented on CHANGELOG.md
> +- I18n Ro, It and Cs.
There are no changes on `ro.json`

```suggestion
- I18n It and Cs.
```

2020-12-17 13:29 UTC, dvm1984 submitted a review, later dismissed

2020-12-17 14:06 UTC, wdsrocha approved these changes
Just organized the commits and formatted the messages (no changes to the translations on my side).

2020-12-17 18:45 UTC, dvm1984 approved these changes

2020-12-17 21:33 UTC, merged