Add address rules for DNK, FIN and SWE
vtex/address-form pull request #311
Opened 2021-01-18 14:47 UTC by garrucho

#### What is the purpose of this pull request?

To add address rules for Denmark, Finland, and Sweden, specifically removing the `state` field, which isn't applicable to them.

Note: the props `country` and `abbr` commonly refers to the country code, but was left empty because was impacting in the "calculate" button from the postalCode field – useful when the specific postalCode rule is unknown.

#### What problem is this solving?

These countries don't use the `state` (from a `city`) to identify the addresses, so our form was confusing the shoppers.

#### How should this be manually tested?

It can be tested on this cart and workspace: https://muji--vtexgame1.myvtex.com/checkout/cart/add/?sku=312&qty=1&seller=1&sc=2

#### Screenshots or example usage

N/A

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2021-01-18 19:52 UTC, darlenedms approved these changes

2021-01-18 20:02 UTC, lucasecdb requested changes

2021-01-18 20:02 UTC, lucasecdb commented on react/country/DNK.js
> +  abbr: null,
you need to fill this in

2021-01-18 20:02 UTC, lucasecdb commented on react/country/FIN.js
> +  abbr: null,
ditto

2021-01-18 20:02 UTC, lucasecdb commented on react/country/SWE.js
> +  abbr: null,
ditto

2021-01-18 20:04 UTC, garrucho commented on react/country/DNK.js
> +  abbr: null,
> Note: the props country and abbr commonly refers to the country code, but was left empty because was impacting in the "calculate" button from the postalCode field – useful when the specific postalCode rule is unknown.

😕

2021-01-18 20:36 UTC, lucasecdb commented on react/country/DNK.js
> +  abbr: null,
which values have you used?

2021-01-18 21:58 UTC, garrucho commented on react/country/DNK.js
> +  abbr: null,
The correspondent from countrycode.org - e.g. SWE and SE for Sweden.

2021-01-18 22:18 UTC, jeffersontuc approved these changes

2021-01-19 12:22 UTC, lucasecdb approved these changes

2021-01-19 13:11 UTC, merged