[4.x] [OMS-1167] Fixed CHL rules for
vtex/address-form pull request #340
Opened 2021-05-04 13:50 UTC by salesfelipe

#### What is the purpose of this pull request?

- FIx https://vtex-dev.atlassian.net/secure/RapidBoard.jspa?rapidView=109&modal=detail&selectedIssue=OMS-1167

#### What problem is this solving?

- We weren't able to save the address "Río Loa 689, Valdivia, Valdivia, Chile" because the state info wasn't correctly set.

#### How should this be manually tested?

- Try to add this address on this workspace: 

https://felipe--geraldinemolina.myvtex.com/account#/addresses

#### Screenshots or example usage

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2021-05-04 14:06 UTC, lucasecdb approved these changes

2021-05-04 14:19 UTC, arthurepc commented on CHANGELOG.md
> +- `CHL` rules for feeling data with Google Maps.
```suggestion
- `CHL` rules when filling data with Google Maps.
```

2021-05-04 14:19 UTC, arthurepc commented on react/country/CHL.js
> +        }
I think you can do something like this:
```suggestion
        address.postalCode = {
          value: countryData.[address.state.value]?.[address.neighborhood.value],
        }
```
I didn't test this code, though

2021-05-04 14:21 UTC, salesfelipe commented on react/country/CHL.js
> +        }
Not really, the optional chaining is fine but I shouldn't touch the field if I don't have a postal code for it.

2021-05-04 14:22 UTC, arthurepc commented on react/country/CHL.js
> +          !address.neighborhood.value
Also:
```suggestion
          !address.state?.value ||
          !address.neighborhood?.value
```

2021-05-04 14:55 UTC, arthurepc approved these changes
Just one comment but non-blocking 🎖️

2021-05-04 14:55 UTC, arthurepc commented on react/country/CHL.js
> +        }
It makes sense. So, you could use the optional chaining in your if-statement instead

2021-05-04 15:17 UTC, garrucho requested changes

2021-05-04 15:17 UTC, garrucho commented on react/country/CHL.js
> +  'Los Ríos': {
We can't change this. It's a breaking change between already registered customers and orderForms that are already using the old `XIV Región` value, makes sense?

2021-05-04 17:40 UTC, arthurepc approved these changes

2021-05-07 14:23 UTC, lucasecdb commented on react/country/CHL.js
> +  'Los Ríos': {
suggestion, can we add a handler in address form to tackle this? change the state for customers with `XIV Región` in the order form to `Los Ríos`?

2021-05-12 12:59 UTC, malvadeza approved these changes

2021-05-12 12:59 UTC, malvadeza commented on react/country/CHL.js
> +        ) {
Well, if you can use optional chaining (like lines [530](https://github.com/vtex/address-form/pull/340/files#diff-a5e922924a10360dcff919c05d716b405072ba16eae7a1b18983803416e7732bR530) and [531](https://github.com/vtex/address-form/pull/340/files#diff-a5e922924a10360dcff919c05d716b405072ba16eae7a1b18983803416e7732bR531) you could do something like:

```suggestion
        if (countryData[address.state.value]?.[address.neighborhood.value]) {
```

but def not blocking.

2021-05-12 17:41 UTC, merged