[3.x] [OMS-1167] Fixed CHL rules for
vtex/address-form pull request #341
Opened 2021-05-04 14:00 UTC by salesfelipe

#### What is the purpose of this pull request?

- FIx https://vtex-dev.atlassian.net/secure/RapidBoard.jspa?rapidView=109&modal=detail&selectedIssue=OMS-1167

#### What problem is this solving?

- We weren't able to save the address "Río Loa 689, Valdivia, Valdivia, Chile" because the state info wasn't correctly set.

#### How should this be manually tested?

- Try to add this address on this workspace: 

https://felipe--geraldinemolina.myvtex.com/account#/addresses

Same as: https://github.com/vtex/address-form/pull/340

#### Screenshots or example usage

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2021-05-04 14:06 UTC, lucasecdb submitted a review, later dismissed

2021-05-04 14:56 UTC, arthurepc approved these changes
I have the same comments I've made in https://github.com/vtex/address-form/pull/340

2021-05-04 15:11 UTC, lucasecdb submitted a review, later dismissed

2021-05-04 15:31 UTC, garrucho requested changes

2021-05-04 15:31 UTC, garrucho commented on react/country/CHL.js
> +  'Los Ríos': {
Same as: https://github.com/vtex/address-form/pull/340/files#r625872797

2021-05-04 17:42 UTC, arthurepc submitted a review, later dismissed

2021-05-11 13:01 UTC, lucasecdb submitted a review, later dismissed

2021-05-12 13:00 UTC, malvadeza submitted a review, later dismissed

2021-05-12 17:41 UTC, lschlee approved these changes

2021-05-12 17:47 UTC, garrucho approved these changes

2021-05-12 17:47 UTC, malvadeza approved these changes

2021-05-12 17:54 UTC, jeffersontuc approved these changes

2021-05-12 17:55 UTC, merged