Creation of crowdin file
vtex/address-form pull request #381
Opened 2021-07-08 21:10 UTC by daniserejo

#### What is the purpose of this pull request?

Creation of crowdin file

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2021-07-09 12:50 UTC, camilavcoutinho requested changes

2021-07-09 12:50 UTC, camilavcoutinho commented on CHANGELOG.md
> +### Added
```suggestion
### Fixed
```

2021-07-09 17:27 UTC, lucasecdb reviewed
you don't need to update the changelog, as there isn't any changes to release here, can you undo it?

2021-07-13 14:22 UTC, camilavcoutinho approved these changes

2021-07-15 18:22 UTC, lucasecdb approved these changes

2021-07-15 18:22 UTC, merged