Add more cities to counties(with more than 50k people)
vtex/address-form pull request #388
Opened 2021-07-22 10:54 UTC by mada-vtex

#### What is the purpose of this pull request?

Complete the cities list with some more.The cities that had more than 50k people were listed in a different page of the gvt site, so they were missed from the initial cities list. 

#### What problem is this solving?

The cities that had more than 50k people were listed in a different page of the gvt site, so they were missed from the initial cities list. These cities were not searchable in the checkout form.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2021-07-22 12:56 UTC, lucasecdb requested changes

2021-07-22 12:56 UTC, lucasecdb commented on CHANGELOG.md
> +## [3.18.6] - 2021-07-22
you don't need to add this line when creating a PR to the `main` branch of this repository, and for the `4.x` branch you should use [`releasy`](https://github.com/vtex/releasy/) to create this tag for you (since it will also create a git tag and a bump commit)

```suggestion
```

2021-07-22 13:06 UTC, lucasecdb approved these changes

2021-07-22 14:45 UTC, vtexdaniel approved these changes
Ai 2 Madalina, stai jos!

2021-07-26 17:41 UTC, ericbreno approved these changes

2021-07-26 18:52 UTC, mihainutiu-vtex approved these changes

2021-07-26 19:13 UTC, merged