fix italian translations
vtex/address-form pull request #397
Opened 2021-08-12 16:53 UTC by camilavcoutinho

#### What is the purpose of this pull request?

Fix Italian translations

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2021-08-12 16:55 UTC, Silvia-Spela approved these changes

2021-08-28 03:04 UTC, Silvia-Spela approved these changes

2021-08-30 12:32 UTC, lucasecdb commented
@camilavcoutinho can you rebase? there is a conflict in the changelog

2021-08-30 13:26 UTC, lucasecdb requested changes

2021-08-30 13:26 UTC, lucasecdb commented on messages/it.json
> +  "address-form.field.addressLine1": "Via e numero civico",
@camilavcoutinho I think you lost some of the modifications :-/

this should be only "Via" right? and for the number below it should be "Numero civico"

2021-08-30 13:33 UTC, camilavcoutinho commented on messages/it.json
> +  "address-form.field.addressLine1": "Via e numero civico",
Yeah! I think when I did the rebase, I lost the modifications. Sorry about that! I'll fix it right away.

2021-08-30 13:59 UTC, lucasecdb approved these changes
nice! ✨

2021-08-30 14:00 UTC, Silvia-Spela approved these changes

2021-08-30 17:07 UTC, merged