L18n 4x europe
vtex/address-form pull request #428
Opened 2021-11-22 12:06 UTC by kaibrockelt

#### What is the purpose of this pull request?

adding 12 more european countries for the address form validation

#### What problem is this solving?

Motorola is active in these countries already, we had an issue where a Dutch zip code was used to order on the belgian site. 

#### How should this be manually tested?
throw zip codes towards the UI, compare the list of regions.
#### Screenshots or example usage
--
#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2021-11-29 09:19 UTC, kaibrockelt commented
Hi!
Can we get the approval through? @wdsrocha @jeffersontuc  
That release is important to motorola europe a lot!

2022-01-03 14:37 UTC, jeffersontuc approved these changes
LGTM! Good job! 🚀

2022-01-05 15:18 UTC, wdsrocha requested changes
It's missing the CHANGELOG, but I'll add it myself and deploy it soon, no need to fix anything

2022-01-05 20:45 UTC, wdsrocha commented on CHANGELOG.md
> +[4.13.1]: https://github.com/vtex/address-form/compare/v4.13.0...v4.13.1
🤷
```suggestion
```

2022-01-05 20:51 UTC, wdsrocha approved these changes

2022-01-05 20:53 UTC, jeffersontuc approved these changes

2022-01-05 20:53 UTC, merged