address fixes
vtex/address-form pull request #439
Opened 2022-02-04 18:43 UTC by camilavcoutinho

#### What is the purpose of this pull request?

Ecuador city names and Iraq address rules fixes.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2022-02-07 13:17 UTC, wdsrocha commented on react/country/PER.js
> -  },
This isn't mentioned in the changelogl. Was that change intentional?

2022-02-07 13:18 UTC, wdsrocha commented on react/country/IRQ.js
> +      optionsMap: getTwoLevels(countryData),
Why this change was necessary? It looks like those two array elements just swapped positions but I could be missing something

2022-02-07 13:19 UTC, lucasecdb requested changes

2022-02-07 13:19 UTC, lucasecdb commented on react/country/ECU.js
> +    Catamayo: '0011',
we can't rename the city/state names like this 😅 this would break existing carts that are using the "old" name

we can, though, add a new name and keep the previous one if it is incorrect in any way

2022-02-08 13:09 UTC, camilavcoutinho commented on react/country/IRQ.js
> +      optionsMap: getTwoLevels(countryData),
Because of the property basedOn. Putting the city array before state with the property basedOn: 'state', would interfere and block this property in the checkout flow.

2022-02-08 13:13 UTC, camilavcoutinho commented on react/country/ECU.js
> +    Catamayo: '0011',
@lucasecdb all these changes were made in pair coding with @jeffersontuc. We've tested it in a workspace already. And knowing about all the particularities regarding these changes, that is why I put it in the checkout-localization channel to understand the change.

2022-02-15 12:15 UTC, lucasecdb requested changes

2022-02-15 12:15 UTC, lucasecdb commented on react/country/PER.js
> -  Callao: {
wouldn't this removal affect existing carts and orders?

2022-02-15 13:30 UTC, jeffersontuc commented on react/country/PER.js
> -  Callao: {
At first, it won't because this info shouldn't be there, since Callao is not a department. So we are presuming that this option was never used.

2022-02-15 13:46 UTC, lucasecdb commented on react/country/PER.js
> -  Callao: {
for sanity check, is there any way we can see if this was used in any order/cart?

2022-02-15 17:32 UTC, jeffersontuc commented on react/country/PER.js
> -  Callao: {
Good question! I don't think there's an easy way 😢

2022-02-15 18:44 UTC, lucasecdb commented on react/country/PER.js
> -  Callao: {
I think it is important that we do this check before publishing these changes, to avoid creating any issues on our customers

2022-02-15 18:47 UTC, lucasecdb approved these changes

2022-02-15 18:52 UTC, merged