Add Placeholder for ZAF market
vtex/address-form pull request #448
Opened 2022-03-21 10:25 UTC by dcionevtex

#### What is the purpose of this pull request?

Added the placeholder message for ZAF locale for TFG client in south africa
address-form.geolocation.example.ZAF

#### What problem is this solving?
add placeholder on checkout for ZAF because checkout is loading the "default" locale in some cases.

#### How should this be manually tested?
Please deploy the app to
 https://checkoutnocustom--thefoschini.myvtex.com/checkout/cart/add/?sku=1&qty=1&seller=1&sc=1
 
#### Screenshots or example usage

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2022-03-21 14:03 UTC, camilavcoutinho approved these changes
LGTM ✨

2022-03-22 17:10 UTC, lucasecdb requested changes
please fix the changelog, the bot will automatically create the new version tag after merging the PR 🙂

2022-03-22 17:10 UTC, lucasecdb commented on CHANGELOG.md
> +## [3.24.6] -
```suggestion
### Changed
```

2022-03-22 17:13 UTC, lucasecdb submitted a review, later dismissed

2022-03-22 17:19 UTC, camilavcoutinho reviewed
I think Changelog needs to be changed

2022-03-22 17:20 UTC, lucasecdb approved these changes

2022-03-22 17:55 UTC, camilavcoutinho approved these changes

2022-03-22 18:26 UTC, merged