Fix number not appearing using geolocation in NZL
vtex/address-form pull request #519
Opened 2023-05-11 19:19 UTC by camilavcoutinho

#### What is the purpose of this pull request?

Fixing the street/house number not appearing on the address form after an address is selected. Customers are negatively impacted by the missing street number, assuming the order will not be delivered.

It relates to closed PR https://github.com/vtex/address-form/pull/516

#### What problem is this solving?

to replicate the scenario, access vineonline.myvtex.com, add any item to your cart and proceed to checkout. When asked for your address, start typing 48 Avalon Drive ... full address includes Forest Lake, 3200, Hamilton City, but we use Google Maps API for auto-complete. When you select the address, you will notice that the street number (48 in this case) goes missing. Hopefully with this deploy, that number will appear during the checkout process on the address form.

#### How should this be manually tested?

https://localization--vineonline.myvtex.com/checkout/#/shipping

#### Screenshots or example usage

#### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2023-05-12 12:12 UTC, vmarcosp commented
It seems that the bug has been fixed with these changes.
Any thoughts on this @jeffersontuc and @lucasecdb?

2023-05-15 04:05 UTC, dvm1984 commented
> It seems that the bug has been fixed with these changes. Any thoughts on this @jeffersontuc and @lucasecdb?

Hi @vmarcosp @jeffersontuc @lucasecdb - please prioritize this deploy, it is a go-live blocker for the client. Go-live is meant to happen on Wednesday New Zealand time - meaning Tuesday for us in Brazil. Without this fix there is no go-live.

2023-05-15 12:10 UTC, jeffersontuc approved these changes

2023-05-15 12:11 UTC, jeffersontuc commented on CHANGELOG.md
> +- Add number field using geolocation in New Zealand (NZL) file.
other than that, LGTM ✨

2023-05-15 12:34 UTC, lucasecdb requested changes

2023-05-15 13:15 UTC, merged

2023-05-15 14:21 UTC, dvm1984 commented
amazing work, thank you so much !