Fix postal code rules using geolocation
vtex/address-form pull request #524
Opened 2023-05-24 17:33 UTC by camilavcoutinho

#### What is the purpose of this pull request?

Fix Postal code rules when using geolocation. It relates to shared [KI](https://docs.google.com/document/d/1HxyxtgwT7pvtv2Vzrz-gHEjhVNGPgYXtwt7VVZtseN8/edit#heading=h.tglo77yl0lf5) between OMS and Checkout. 

Added the require condition to all missing files and fixed it's validation, taking into account [UPS documentation](https://www.ups.com/worldshiphelp/WSA/ENU/AppHelp/mergedProjects/CORE/Codes/Countries_Territories_Requiring_Postal_Codes.htm). 

It relates to https://github.com/vtex/address-form/pull/514

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2023-05-25 17:41 UTC, vmarcosp commented
Some tests are failing due to these changes in the rules. Could you please update the ones that are broken?

2023-06-13 18:43 UTC, jeffersontuc requested changes

2023-06-13 18:43 UTC, jeffersontuc commented on react/country/ARG.ts
> +      required: true,
Is it the `postalCode` really required in geolocation mode for Argentina? For instance, the address `Corrientes 240, Las Varillas, Córdoba, Argentina` doesn't return a postal code.

2023-06-13 18:43 UTC, jeffersontuc commented on react/country/ARG.ts
> +      required: true,
To make the change from `false` to `true` we gotta make sure that we will always have this information for all the addresses on this country. Otherwise, this change is going to block some users from finishing purchases.

2023-06-19 19:21 UTC, sheilagomes commented
> Codewise the PR looks good to me. But I'm not so sure about the changes from `required: false` to `required: true` in some of these countries. Are we really sure about that? Those changes could prevent many users from purchasing in those countries. eyes

Fixed!

2023-06-21 17:36 UTC, jeffersontuc commented on react/country/GTM.ts
> -      required: true,
Maybe we should keep that as `true`?

2023-06-21 17:36 UTC, jeffersontuc commented on react/country/JAM.ts
> -      required: true,
ditto

2023-06-21 17:56 UTC, sheilagomes commented on react/country/GTM.ts
> -      required: true,
done!

2023-06-21 17:56 UTC, sheilagomes commented on react/country/JAM.ts
> -      required: true,
fixed!

2023-06-21 17:56 UTC, sheilagomes approved these changes

2023-06-27 15:11 UTC, merged