fix postal code rules using geolocation
vtex/address-form pull request #525
Opened 2023-05-24 18:28 UTC by camilavcoutinho

#### What is the purpose of this pull request?

Fix Postal code rules when using geolocation. It relates to shared [KI](https://docs.google.com/document/d/1HxyxtgwT7pvtv2Vzrz-gHEjhVNGPgYXtwt7VVZtseN8/edit#heading=h.tglo77yl0lf5) between OMS and Checkout.

Added the require condition to all missing files and fixed it's validation, taking into account [UPS documentation](https://www.ups.com/worldshiphelp/WSA/ENU/AppHelp/mergedProjects/CORE/Codes/Countries_Territories_Requiring_Postal_Codes.htm).

It relates to https://github.com/vtex/address-form/pull/514 and https://github.com/vtex/address-form/pull/524

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2023-05-25 17:34 UTC, vmarcosp commented
Since it's a fix, shouldn't it be a patch version instead of a minor?

2023-05-30 14:43 UTC, vmarcosp commented
@camilavcoutinho there is a unit test broken, could you please update the test? You can follow this [commit](https://github.com/vtex/address-form/pull/524/commits/419e63a3fc2bba972b0ac8a998474962e1c8f310) as an example.

2023-06-13 19:11 UTC, jeffersontuc requested changes

2023-06-13 19:11 UTC, jeffersontuc commented on react/country/ARG.js
> +      required: true,
The same as https://github.com/vtex/address-form/pull/524#discussion_r1228554010

2023-06-21 19:01 UTC, jeffersontuc approved these changes
LGTM! 🚀

2023-06-21 19:41 UTC, vmarcosp approved these changes

2023-06-27 15:38 UTC, merged