Adding VIR country rules for address-form
vtex/address-form pull request #529
Opened 2023-07-06 11:22 UTC by GeorgeLimaDev

#### What is the purpose of this pull request?

It relates to task [LOC-11085](https://vtex-dev.atlassian.net/browse/LOC-11085).

#### How should this be manually tested?
Test store: https://george--worldwidegolf.myvtex.com/?

#### Screenshots or example usage
![image](https://github.com/vtex/address-form/assets/106821144/2f0269b6-2ca5-4298-a136-94a96e1f66c2)

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2023-07-06 19:23 UTC, camilavcoutinho approved these changes

2023-07-14 13:57 UTC, evertonstrack requested changes

2023-07-14 13:57 UTC, evertonstrack commented on react/country/VIR.js
> +
In cases where we have the `number` field hidden in the form settings, we need to add the `number` field as `required: false` and `notApplicable: true` in `geolocation` configuration, to prevent the user from being unable to proceed to payment when geolocation is not activated. It was an issue we discovered and [fixed a few months ago in other countries configs](https://github.com/vtex/address-form/pull/512).

You can check out the [configuration file for France](https://github.com/vtex/address-form/blob/main/react/country/FRA.ts#L84C5-L89C7) as an example.

2023-07-14 13:58 UTC, evertonstrack reviewed
In cases where we have the `number` field hidden in the form settings, we need to add the `number` field as `required: false` and `notApplicable: true` in `geolocation` configuration, to prevent the user from being unable to proceed to payment when geolocation is not activated. It was an issue we discovered and [fixed a few months ago in other countries configs](https://github.com/vtex/address-form/pull/512).

You can check out the [configuration file for France](https://github.com/vtex/address-form/blob/main/react/country/FRA.ts#L84C5-L89C7) as an example.

2023-07-14 18:04 UTC, evertonstrack approved these changes
LGTM! 🚀

2023-08-23 13:41 UTC, merged