Loc/14701 4x
vtex/address-form pull request #571
Opened 2024-05-13 16:54 UTC by GeorgeLimaDev

#### What is the purpose of this pull request?

It relates to the task [LOC-14701](https://vtex-dev.atlassian.net/browse/LOC-14701). Adds Hungarian translations to the 4.x branch. This PR is a reflection of #570 on the main branch.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2024-05-13 17:00 UTC, sheilagomes approved these changes

2024-05-22 15:38 UTC, jeffersontuc requested changes

2024-05-22 15:38 UTC, jeffersontuc commented on CHANGELOG.md
> +
could you fix this CHANGELOG?

2024-05-22 16:40 UTC, jeffersontuc approved these changes

2024-05-22 16:42 UTC, merged